export default [
  {
    id: 1,
    tipo: "camisaFeminina/",
    nome: "Camisa Preta",
    valor: 45.99,
    label: "camisapreta",
    foto: "/img/camisas/camisaPreta1.jpeg",
  },
  {
    id: 2,
    tipo: "camisaFeminina/",
    nome: "Camisa azul",
    valor: 45.99,
    label: "camisaazul",
    foto: "/img/camisas/camisaPreta2.jpeg",
  },
  {
    id: 3,
    tipo: "camisaFeminina/",
    nome: "Camisa rosa",
    valor: 45.99,
    label: "camisarosa",
    foto: "/img/camisas/camisaPreta3.jpeg",
  },

  {
    id: 4,
    tipo: "camisaFeminina/",
    nome: "Camisa Preta2",
    valor: 45.99,
    label: "camisapreta2",
    foto: "/img/camisas/camisaPreta4.jpeg",
  },

  {
    id: 5,
    tipo: "camisaFeminina/",
    nome: "Camisa azul2",
    valor: 45.99,
    label: "camisaazul2",
    foto: "/img/camisas/camisa2.jpg",
  },
  {
    id: 6,
    tipo: "camisaFeminina/",
    nome: "Camisa rosa2",
    valor: 45.99,
    label: "camisarosa2",
    foto: "/img/camisas/camisa3.jpg",
  },
  {
    id: 7,
    tipo: "camisaFeminina/",
    nome: "Camisa Preta3",
    valor: 45.99,
    label: "camisapreta3",
    foto: "/img/camisas/camisa1.jpg",
  },
  {
    id: 8,
    tipo: "camisaFeminina/",
    nome: "Camisa azul3",
    valor: 45.99,
    label: "camisaazul3",
    foto: "/img/camisas/camisa2.jpg",
  },
  {
    id: 9,
    tipo: "camisaFeminina/",
    nome: "Camisa rosa3",
    valor: 45.99,
    label: "camisarosa3",
    foto: "/img/camisas/camisa3.jpg",
  },
];
